# Generated by Django 3.2.16 on 2022-12-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('ano', models.CharField(max_length=255)),
                ('kilometragem', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('valorPromocao', models.FloatField(blank=True, null=True)),
                ('is_promocao', models.BooleanField(blank=True, default=False, null=True)),
                ('is_disponivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carro',
                'ordering': ['marca'],
            },
        ),
        migrations.CreateModel(
            name='FotosCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('is_principal', models.BooleanField(blank=True, default=False, null=True)),
                ('fotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='produtos.carro')),
            ],
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
