# Generated by Django 3.2.16 on 2022-12-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20221205_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'ordering': ['valor'], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
    ]
