# Generated by Django 3.2.16 on 2022-12-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chavePix',
        ),
        migrations.RemoveField(
            model_name='user',
            name='financeiro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nivelAcesso',
            field=models.CharField(default='1', max_length=25),
        ),
    ]
